@host=http://localhost:5013
PUT {{host}}/employees/update
Content-Type: application/json

{
  "id": {
      "value": "88e95a6d-188c-4be8-b975-17aa0e4f3961"
  },
  "fullName": "Швецова Яна Григорьевна",
  "position": "старший эколог"
}