// <auto-generated />
using System;
using MaximCRMTestProject.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MaximCRMTestProject.Infrastructure.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    [Migration("20230609134151_Initial_Create")]
    partial class Initial_Create
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MaximCRMTestProject.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FullName")
                        .IsUnique();

                    b.ToTable("Employees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("35144ed8-6595-4b5a-9d2d-0d8595a40ea8"),
                            FullName = "Калмыков Макар Владимирович",
                            Position = "кризис-менеджер"
                        },
                        new
                        {
                            Id = new Guid("40427991-0373-445b-9a81-4f4a0a13b6b7"),
                            FullName = "Швецова Яна Григорьевна",
                            Position = "эколог"
                        },
                        new
                        {
                            Id = new Guid("255d08eb-4283-41fd-bdae-b69324afed57"),
                            FullName = "Назаров Александр Львович",
                            Position = "рыбак"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
